### ISSUE TITLE
项目构建工具要不要换Gulp

### ISSUE THREAD

**Issue by hygkui** [cloud-bean/hbg#2]
Gulp比Grunt更易用，速度更快，推荐。

**Comment by xinnix** [comment]
建议先别换，按照mean.js目前的架构来。等上线后，后期可以进行迭代修改，目前刚搞清楚grunt的运作模式

**Comment by hygkui** [comment]
两个的流程差不多，而且配置一次就不用动了。我这里有完整的实例架构，我建立一个分支，你回头看下。

**Comment by hygkui** [comment]
采用Gulp。
